import { Button, VerticalBox, HorizontalBox, TextEdit, LineEdit, Spinner } from "std-widgets.slint";

export global PathSelectorGlobal {
    callback browse(string) -> string;
    callback open(string);
}

export component PathSelector inherits HorizontalBox {
    in-out property <string> display <=> text.text;
    in-out property <string> path <=> edit.text;

    callback accepted(string);

    alignment: start;
    spacing: 0.5rem;

    text := Text {
        vertical-alignment: center;
    }

    edit := LineEdit {
        preferred-width: parent.width;

        edited => {
            parent.path = self.text;
        }

        accepted => {
            parent.path = self.text;
            parent.accepted(parent.path);
        }
    }

    Button {
        text: "Browse";

        clicked => {
            parent.path = PathSelectorGlobal.browse(parent.path);
        }
    }

    Button {
        text: "Open";

        clicked => {
            PathSelectorGlobal.open(parent.path);
        }
    }

}

export component AppWindow inherits Window {
    min-width: 48rem;
    min-height: 24rem;

    VerticalBox {
        alignment: center;
        spacing: 0.5rem;
        padding-top: 1rem;
        padding-bottom: 1rem;
        padding-left: 2rem;
        padding-right: 2rem;

        PathSelector {
            display: "Source";
        }

        PathSelector {
            display: "Destination";
        }

        Button {
            text: "Confirm";
            primary: true;
            clicked => {

            }
        }
    }
}
