import { Button, VerticalBox, HorizontalBox, TextEdit, LineEdit, Spinner, ComboBox } from "std-widgets.slint";

export global PathSelectorGlobal {
    callback browse(string) -> string;
    callback open(string);
}

export component PathSelector inherits HorizontalBox {
    in-out property <string> display <=> text.text;
    in-out property <string> path <=> edit.text;

    callback accepted(string);
    callback edited(string);

    alignment: start;
    spacing: 0.5rem;

    text := Text {
        vertical-alignment: center;
    }

    edit := LineEdit {
        preferred-width: parent.width;

        edited => {
            parent.path = self.text;
            parent.edited(parent.path);
        }

        accepted => {
            parent.path = self.text;
            parent.accepted(parent.path);
        }
    }

    Button {
        text: "Browse";

        clicked => {
            parent.path = PathSelectorGlobal.browse(parent.path);
        }
    }

    Button {
        text: "Open";

        clicked => {
            PathSelectorGlobal.open(parent.path);
        }
    }

}

export component AppWindow inherits Window {
    in-out property <[string]> packs <=> packs.model;
    in-out property <string> selected-display <=> packs.current-value;
    in-out property <int> selected <=> packs.current-index;
    in-out property <bool> linked: false;
    in-out property <string> error;

    in-out property <string> mmc-path <=> mmc.path;
    in-out property <string> ftb-path <=> ftb.path;

    in-out property <bool> pack-icon-exists: false;
    in-out property <image> pack-icon;

    callback mmc-path-edited(string);
    callback ftb-path-edited(string);

    callback load-packs() -> [string];

    callback selected-change <=> packs.selected;
    callback accepted <=> button.clicked;

    callback refresh <=> refresh.clicked;

    title: "FTB Link";
    min-width: 48rem;
    min-height: 16rem;

    VerticalBox {
        alignment: center;
        spacing: 0.5rem;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
        padding-left: 1.5rem;
        padding-right: 1.5rem;

        mmc := PathSelector {
            display: "Prism/MultiMC";

            edited(s) => {
                root.mmc-path-edited(s);
            }

            accepted(s) => {
                root.mmc-path-edited(s);
            }
        }

        ftb := PathSelector {
            display: "FTB";

            edited(s) => {
                root.ftb-path-edited(s);
            }

            accepted(s) => {
                root.ftb-path-edited(s);
            }
        }

        HorizontalBox {
            if (pack-icon-exists): Image {
                source: root.pack-icon;
                max-height: 2rem;
                max-width: 2rem;
            }

            packs := ComboBox {

            }

            refresh := Button {
                text: "Refresh";
            }

            button := Button {
                text: linked ? "Unlink" : "Link";
                primary: true;
            }
        }

        if (error != ""): Text {
            horizontal-alignment: center;
            text: error;
        }
    }
}
